name: ECS Deploy
description: Deploy to ECS
author: https://github.com/buildkite
requirements:
  - aws
  - jq
configuration:
  properties:
    cluster:
      type: string
    service:
      type: string
    task-definition:
      type: string
    task-family:
      type: string
    image:
      type: [ string, array ]
    desired-count:
      type: string
    task-role-arn:
      type: string
    target-group:
      type: string
    load-balanccer-name:
      type: string
    target-container-name:
      type: string
    target-container-port:
      type: integer
    execution-role:
      type: string
    deployment-config:
      type: string
    require-capabilities:
      type: string
    network-mode:
      type: string
    fargate_cpu:
      type: string
    fargate_memory:
      type: string
  required:
    - cluster
    - service
    - task-definition
    - task-family
    - image
